// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POS.Desktop.Data;

#nullable disable

namespace POS.Desktop.Data.Migrations.Local
{
    [DbContext(typeof(PosLocalDbContext))]
    [Migration("20260528094204_AddLocalOrderPaymentTables")]
    partial class AddLocalOrderPaymentTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("POS.Desktop.Data.LocalEntities.LocalCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.HasIndex("TenantId", "SortOrder");

                    b.ToTable("LocalCategories", null, t =>
                        {
                            t.HasCheckConstraint("CK_LocalCategory_Code_NotEmpty", "Code <> ''");

                            t.HasCheckConstraint("CK_LocalCategory_Name_NotEmpty", "Name <> ''");

                            t.HasCheckConstraint("CK_LocalCategory_TenantId", "TenantId > 0");
                        });
                });

            modelBuilder.Entity("POS.Desktop.Data.LocalEntities.LocalEmployee", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MustChangePin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("PinHash")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("PinHashAlgorithm")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PinSalt")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EmployeeNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_LocalEmployees_Tenant_EmployeeNumber");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_LocalEmployees_Tenant_Status");

                    b.ToTable("LocalEmployees", null, t =>
                        {
                            t.HasCheckConstraint("CK_LocalEmployee_DisplayName_NotEmpty", "DisplayName <> ''");

                            t.HasCheckConstraint("CK_LocalEmployee_EmployeeNumber_NotEmpty", "EmployeeNumber <> ''");

                            t.HasCheckConstraint("CK_LocalEmployee_TenantId", "TenantId > 0");
                        });
                });

            modelBuilder.Entity("POS.Desktop.Data.LocalEntities.LocalEmployeeLocationRole", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndsOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PermissionSetCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartsOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EmployeeId", "Role")
                        .IsUnique()
                        .HasDatabaseName("UX_LocalEmployeeLocationRoles_TenantWide")
                        .HasFilter("LocationId IS NULL");

                    b.HasIndex("TenantId", "LocationId", "Role")
                        .HasDatabaseName("IX_LocalEmployeeLocationRoles_Tenant_Location_Role");

                    b.HasIndex("TenantId", "EmployeeId", "LocationId", "Role")
                        .IsUnique()
                        .HasDatabaseName("UX_LocalEmployeeLocationRoles_Scoped")
                        .HasFilter("LocationId IS NOT NULL");

                    b.ToTable("LocalEmployeeLocationRoles", null, t =>
                        {
                            t.HasCheckConstraint("CK_LocalEmployeeLocationRole_EmployeeId", "EmployeeId > 0");

                            t.HasCheckConstraint("CK_LocalEmployeeLocationRole_Role_NotEmpty", "Role <> ''");

                            t.HasCheckConstraint("CK_LocalEmployeeLocationRole_TenantId", "TenantId > 0");
                        });
                });

            modelBuilder.Entity("POS.Desktop.Data.LocalEntities.LocalItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CatalogVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultTaxRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultUnitOfMeasureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTrackedInventory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CategoryId");

                    b.HasIndex("TenantId", "ItemCode")
                        .IsUnique();

                    b.HasIndex("TenantId", "Name");

                    b.ToTable("LocalItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_LocalItem_Code_NotEmpty", "ItemCode <> ''");

                            t.HasCheckConstraint("CK_LocalItem_Name_NotEmpty", "Name <> ''");

                            t.HasCheckConstraint("CK_LocalItem_TenantId", "TenantId > 0");
                        });
                });

            modelBuilder.Entity("POS.Desktop.Data.LocalEntities.LocalItemIdentifier", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdentifierType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentifierValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemVariantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IdentifierValue");

                    b.HasIndex("TenantId", "ItemVariantId");

                    b.ToTable("LocalItemIdentifiers", null, t =>
                        {
                            t.HasCheckConstraint("CK_LocalItemIdentifier_TenantId", "TenantId > 0");

                            t.HasCheckConstraint("CK_LocalItemIdentifier_Value_NotEmpty", "IdentifierValue <> ''");
                        });
                });

            modelBuilder.Entity("POS.Desktop.Data.LocalEntities.LocalItemPrice", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CompareAtPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTaxIncluded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemVariantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriceListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitOfMeasureId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ItemVariantId", "PriceListId");

                    b.ToTable("LocalItemPrices", null, t =>
                        {
                            t.HasCheckConstraint("CK_LocalItemPrice_TenantId", "TenantId > 0");

                            t.HasCheckConstraint("CK_LocalItemPrice_UnitPrice", "UnitPrice >= 0");
                        });
                });

            modelBuilder.Entity("POS.Desktop.Data.LocalEntities.LocalItemVariant", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CatalogVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSellable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SKU")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TaxRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitOfMeasureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VariantCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ItemId");

                    b.HasIndex("TenantId", "SKU");

                    b.HasIndex("TenantId", "VariantCode")
                        .IsUnique();

                    b.ToTable("LocalItemVariants", null, t =>
                        {
                            t.HasCheckConstraint("CK_LocalItemVariant_Code_NotEmpty", "VariantCode <> ''");

                            t.HasCheckConstraint("CK_LocalItemVariant_TenantId", "TenantId > 0");
                        });
                });

            modelBuilder.Entity("POS.Desktop.Data.LocalEntities.LocalOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("CatalogVersion")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ChangeAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FulfillmentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestPhone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OriginalOrderId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PriceListId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReceiptTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RuleVersion")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SubtotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SyncedOn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TerminalId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TerminalSequence")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("VoidedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ReceiptNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_LocalOrders_Tenant_ReceiptNumber");

                    b.HasIndex("TenantId", "TerminalId", "Status")
                        .HasDatabaseName("IX_LocalOrders_Tenant_Terminal_Status");

                    b.HasIndex("TenantId", "TerminalId", "TerminalSequence")
                        .IsUnique()
                        .HasDatabaseName("UX_LocalOrders_Tenant_Terminal_Sequence");

                    b.ToTable("LocalOrders", null, t =>
                        {
                            t.HasCheckConstraint("CK_LocalOrder_ChangeAmount", "ChangeAmount >= 0");

                            t.HasCheckConstraint("CK_LocalOrder_EmployeeId", "EmployeeId > 0");

                            t.HasCheckConstraint("CK_LocalOrder_LocationId", "LocationId > 0");

                            t.HasCheckConstraint("CK_LocalOrder_PaidAmount", "PaidAmount >= 0");

                            t.HasCheckConstraint("CK_LocalOrder_SubtotalAmount", "SubtotalAmount >= 0");

                            t.HasCheckConstraint("CK_LocalOrder_TenantId", "TenantId > 0");

                            t.HasCheckConstraint("CK_LocalOrder_TerminalId", "TerminalId > 0");

                            t.HasCheckConstraint("CK_LocalOrder_TotalAmount", "TotalAmount >= 0");
                        });
                });

            modelBuilder.Entity("POS.Desktop.Data.LocalEntities.LocalOrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AuthorizedByEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("CatalogVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ItemVariantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OriginalOrderLineId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PriceListId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReasonCodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SKU")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TaxRate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TaxRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TerminalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitOfMeasureCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("VariantName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_LocalOrderLines_OrderId");

                    b.HasIndex("TenantId", "OrderId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_LocalOrderLines_Tenant_OrderId_LineNumber");

                    b.ToTable("LocalOrderLines", null, t =>
                        {
                            t.HasCheckConstraint("CK_LocalOrderLine_GrossAmount", "GrossAmount >= 0");

                            t.HasCheckConstraint("CK_LocalOrderLine_LineNumber", "LineNumber > 0");

                            t.HasCheckConstraint("CK_LocalOrderLine_LocationId", "LocationId > 0");

                            t.HasCheckConstraint("CK_LocalOrderLine_NetAmount", "NetAmount >= 0");

                            t.HasCheckConstraint("CK_LocalOrderLine_Quantity", "Quantity > 0");

                            t.HasCheckConstraint("CK_LocalOrderLine_TenantId", "TenantId > 0");

                            t.HasCheckConstraint("CK_LocalOrderLine_TerminalId", "TerminalId > 0");

                            t.HasCheckConstraint("CK_LocalOrderLine_UnitPrice", "UnitPrice >= 0");
                        });
                });

            modelBuilder.Entity("POS.Desktop.Data.LocalEntities.LocalPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorizationCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AuthorizedAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CapturedAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardBrand")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardLast4")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalPaymentReference")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OriginalPaymentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentToken")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ProcessedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReconciledOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresReconciliation")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SyncedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenderMethodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TerminalId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TerminalSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_LocalPayments_OrderId");

                    b.HasIndex("TenantId", "OrderId", "TenderMethodId")
                        .HasDatabaseName("IX_LocalPayments_Tenant_OrderId_TenderMethod");

                    b.ToTable("LocalPayments", null, t =>
                        {
                            t.HasCheckConstraint("CK_LocalPayment_Amount", "Amount > 0");

                            t.HasCheckConstraint("CK_LocalPayment_LocationId", "LocationId > 0");

                            t.HasCheckConstraint("CK_LocalPayment_TenantId", "TenantId > 0");

                            t.HasCheckConstraint("CK_LocalPayment_TenderMethodId", "TenderMethodId > 0");

                            t.HasCheckConstraint("CK_LocalPayment_TerminalId", "TerminalId > 0");
                        });
                });

            modelBuilder.Entity("POS.Desktop.Data.LocalEntities.LocalReasonCode", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresManagerApproval")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("LocalReasonCodes", null, t =>
                        {
                            t.HasCheckConstraint("CK_LocalReasonCode_Code_NotEmpty", "Code <> ''");

                            t.HasCheckConstraint("CK_LocalReasonCode_Name_NotEmpty", "Name <> ''");

                            t.HasCheckConstraint("CK_LocalReasonCode_TenantId", "TenantId > 0");
                        });
                });

            modelBuilder.Entity("POS.Desktop.Data.LocalEntities.LocalRecoveryJournal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredAction")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionComment")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResolvedByEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ResolvedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RetainUntil")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatePayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TerminalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status", "RecoveryType")
                        .HasDatabaseName("IX_LocalRecoveryJournal_Status_Type");

                    b.HasIndex("TenantId", "CorrelationId")
                        .HasDatabaseName("IX_LocalRecoveryJournal_CorrelationId");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_LocalRecoveryJournal_Tenant_IdempotencyKey");

                    b.HasIndex("TenantId", "OrderId")
                        .HasDatabaseName("IX_LocalRecoveryJournal_Tenant_Order");

                    b.ToTable("LocalRecoveryJournal", (string)null);
                });

            modelBuilder.Entity("POS.Desktop.Data.LocalEntities.LocalRetentionState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastCleanupOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("OldestRetainedBusinessDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TerminalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_LocalRetentionState_Status");

                    b.HasIndex("TenantId", "TerminalId", "Category")
                        .IsUnique()
                        .HasDatabaseName("UX_LocalRetentionState_Tenant_Terminal_Category");

                    b.ToTable("LocalRetentionState", (string)null);
                });

            modelBuilder.Entity("POS.Desktop.Data.LocalEntities.LocalShift", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClosedByEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ClosedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CountedCashAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExpectedCashAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpenedByEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("OpenedOn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OpeningCashAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SyncedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TerminalId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TerminalSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("VarianceAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "TerminalId", "Status")
                        .HasDatabaseName("IX_LocalShifts_Tenant_Terminal_Status");

                    b.HasIndex("TenantId", "TerminalId", "TerminalSequence")
                        .IsUnique()
                        .HasDatabaseName("UX_LocalShifts_Tenant_Terminal_Sequence");

                    b.ToTable("LocalShifts", null, t =>
                        {
                            t.HasCheckConstraint("CK_LocalShift_LocationId", "LocationId > 0");

                            t.HasCheckConstraint("CK_LocalShift_OpenedByEmployeeId", "OpenedByEmployeeId > 0");

                            t.HasCheckConstraint("CK_LocalShift_OpeningCashAmount", "OpeningCashAmount > 0");

                            t.HasCheckConstraint("CK_LocalShift_TenantId", "TenantId > 0");

                            t.HasCheckConstraint("CK_LocalShift_TerminalId", "TerminalId > 0");
                        });
                });

            modelBuilder.Entity("POS.Desktop.Data.LocalEntities.LocalTaxRule", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalculationMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.Property<long>("RuleVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("LocalTaxRules", null, t =>
                        {
                            t.HasCheckConstraint("CK_LocalTaxRule_Code_NotEmpty", "Code <> ''");

                            t.HasCheckConstraint("CK_LocalTaxRule_Name_NotEmpty", "Name <> ''");

                            t.HasCheckConstraint("CK_LocalTaxRule_TenantId", "TenantId > 0");
                        });
                });

            modelBuilder.Entity("POS.Desktop.Data.LocalEntities.LocalTenderMethod", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowsChange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresExternalReference")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenderType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("LocalTenderMethods", null, t =>
                        {
                            t.HasCheckConstraint("CK_LocalTenderMethod_Code_NotEmpty", "Code <> ''");

                            t.HasCheckConstraint("CK_LocalTenderMethod_Name_NotEmpty", "Name <> ''");

                            t.HasCheckConstraint("CK_LocalTenderMethod_TenantId", "TenantId > 0");
                        });
                });

            modelBuilder.Entity("POS.Desktop.Data.LocalEntities.LocalTerminalSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LoggedInOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LoggedOutOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ShiftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TerminalId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TerminalSequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EmployeeId")
                        .HasDatabaseName("IX_LocalTerminalSessions_Tenant_Employee");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_LocalTerminalSessions_Tenant_Status");

                    b.HasIndex("TenantId", "TerminalId", "TerminalSequence")
                        .IsUnique()
                        .HasDatabaseName("UX_LocalTerminalSessions_Tenant_Terminal_Sequence");

                    b.ToTable("LocalTerminalSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_LocalTerminalSession_DisplayName_NotEmpty", "DisplayName <> ''");

                            t.HasCheckConstraint("CK_LocalTerminalSession_EmployeeId", "EmployeeId > 0");

                            t.HasCheckConstraint("CK_LocalTerminalSession_EmployeeNumber_NotEmpty", "EmployeeNumber <> ''");

                            t.HasCheckConstraint("CK_LocalTerminalSession_LocationId", "LocationId > 0");

                            t.HasCheckConstraint("CK_LocalTerminalSession_Role_NotEmpty", "Role <> ''");

                            t.HasCheckConstraint("CK_LocalTerminalSession_TenantId", "TenantId > 0");

                            t.HasCheckConstraint("CK_LocalTerminalSession_TerminalId", "TerminalId > 0");
                        });
                });

            modelBuilder.Entity("POS.Desktop.Data.LocalEntities.LocalUnitOfMeasure", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowsFractionalQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeasurementType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("LocalUnitsOfMeasure", null, t =>
                        {
                            t.HasCheckConstraint("CK_LocalUom_Code_NotEmpty", "Code <> ''");

                            t.HasCheckConstraint("CK_LocalUom_Name_NotEmpty", "Name <> ''");

                            t.HasCheckConstraint("CK_LocalUom_TenantId", "TenantId > 0");
                        });
                });

            modelBuilder.Entity("POS.Desktop.Data.LocalEntities.PaymentReconciliationQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalPaymentReference")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastAttemptOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastResultCode")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastResultMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("NextAttemptOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentToken")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RetainUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenderMethodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TerminalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptOn")
                        .HasDatabaseName("IX_PaymentReconciliationQueue_Status_NextAttempt");

                    b.HasIndex("TenantId", "CorrelationId")
                        .HasDatabaseName("IX_PaymentReconciliationQueue_CorrelationId");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_PaymentReconciliationQueue_Tenant_IdempotencyKey");

                    b.HasIndex("TenantId", "PaymentId")
                        .IsUnique()
                        .HasDatabaseName("UX_PaymentReconciliationQueue_Tenant_Payment");

                    b.ToTable("PaymentReconciliationQueue", (string)null);
                });

            modelBuilder.Entity("POS.Desktop.Data.LocalEntities.PrintQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastAttemptOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrintJobType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PrintedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceiptNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReceiptTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RenderedContent")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RetainUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TerminalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ZReportId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CorrelationId")
                        .HasDatabaseName("IX_PrintQueue_CorrelationId");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_PrintQueue_Tenant_IdempotencyKey");

                    b.HasIndex("TenantId", "OrderId")
                        .HasDatabaseName("IX_PrintQueue_Tenant_Order");

                    b.HasIndex("Status", "Priority", "CreatedOn")
                        .HasDatabaseName("IX_PrintQueue_Status_Priority");

                    b.ToTable("PrintQueue", (string)null);
                });

            modelBuilder.Entity("POS.Desktop.Data.LocalEntities.SyncCursor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastAckedChunkSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastPullToken")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastPushedChunkSequence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastSuccessfulPullOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ServerBackoffUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("StreamName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TerminalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_SyncCursors_Status");

                    b.HasIndex("TenantId", "TerminalId", "StreamName")
                        .IsUnique()
                        .HasDatabaseName("UX_SyncCursors_Tenant_Terminal_Stream");

                    b.ToTable("SyncCursors", (string)null);
                });

            modelBuilder.Entity("POS.Desktop.Data.LocalEntities.SyncOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AckedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ChunkSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastAttemptOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RetainUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TerminalId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TerminalSequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CorrelationId")
                        .HasDatabaseName("IX_SyncOutbox_CorrelationId");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_SyncOutbox_Tenant_IdempotencyKey");

                    b.HasIndex("Status", "BusinessDate", "TerminalSequence")
                        .HasDatabaseName("IX_SyncOutbox_Status_Order");

                    b.HasIndex("TenantId", "TerminalId", "TerminalSequence", "EventType", "EventId")
                        .IsUnique()
                        .HasDatabaseName("UX_SyncOutbox_Tenant_Terminal_Sequence_Event");

                    b.ToTable("SyncOutbox", (string)null);
                });

            modelBuilder.Entity("POS.Desktop.Data.LocalEntities.TerminalProvisioning", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TerminalId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TerminalProvisioning", null, t =>
                        {
                            t.HasCheckConstraint("CK_TerminalProvisioning_Id", "Id = 1");

                            t.HasCheckConstraint("CK_TerminalProvisioning_LocationId", "LocationId IS NULL OR LocationId > 0");

                            t.HasCheckConstraint("CK_TerminalProvisioning_TenantId", "TenantId IS NULL OR TenantId > 0");

                            t.HasCheckConstraint("CK_TerminalProvisioning_TerminalId", "TerminalId IS NULL OR TerminalId > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
